
// This file has been generated by the GUI designer. Do not modify.
namespace QCCTVCameraViewWidget
{
	public partial class CameraView
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action SourceAction;
		
		private global::Gtk.VBox mainBox;
		
		private global::Gtk.Fixed fixbox;
		
		private global::Gtk.Image output;
		
		private global::Gtk.VBox setBox;
		
		private global::Gtk.HBox bottombox;
		
		private global::Gtk.ProgressBar activity;
		
		private global::Gtk.ProgressBar sensitivity;
		
		private global::Gtk.Label fpslabel;
		
		private global::Gtk.Image detect;
		
		private global::Gtk.Image record;
		
		private global::Gtk.Fixed statsBox;
		
		private global::Gtk.EventBox bgstats;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label IPaddresLabel;
		
		private global::Gtk.Label NameLabel;
		
		private global::Gtk.Label FpsLabel;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.EventBox optionbox;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox topbox;
		
		private global::Gtk.ComboBox source_box;
		
		private global::Gtk.Button MotionButton;
		
		private global::Gtk.Button RecordButton;
		
		private global::Gtk.Fixed controls;
		
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QCCTVCameraViewWidget.CameraView
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.SourceAction = new global::Gtk.Action ("SourceAction", global::Mono.Unix.Catalog.GetString ("Source"), null, null);
			this.SourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Source");
			w2.Add (this.SourceAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "QCCTVCameraViewWidget.CameraView";
			// Container child QCCTVCameraViewWidget.CameraView.Gtk.Container+ContainerChild
			this.mainBox = new global::Gtk.VBox ();
			this.mainBox.Name = "mainBox";
			this.mainBox.Spacing = 6;
			// Container child mainBox.Gtk.Box+BoxChild
			this.fixbox = new global::Gtk.Fixed ();
			this.fixbox.WidthRequest = 300;
			this.fixbox.HeightRequest = 200;
			this.fixbox.Name = "fixbox";
			this.fixbox.HasWindow = false;
			// Container child fixbox.Gtk.Fixed+FixedChild
			this.output = new global::Gtk.Image ();
			this.output.Name = "output";
			this.output.Xalign = 0F;
			this.output.Yalign = 0F;
			this.fixbox.Add (this.output);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixbox [this.output]));
			w3.X = -1;
			// Container child fixbox.Gtk.Fixed+FixedChild
			this.setBox = new global::Gtk.VBox ();
			this.setBox.WidthRequest = 300;
			this.setBox.HeightRequest = 30;
			this.setBox.Name = "setBox";
			this.setBox.Spacing = 6;
			// Container child setBox.Gtk.Box+BoxChild
			this.bottombox = new global::Gtk.HBox ();
			this.bottombox.Name = "bottombox";
			this.bottombox.Spacing = 6;
			// Container child bottombox.Gtk.Box+BoxChild
			this.activity = new global::Gtk.ProgressBar ();
			this.activity.WidthRequest = 100;
			this.activity.Name = "activity";
			this.bottombox.Add (this.activity);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.bottombox [this.activity]));
			w4.Position = 0;
			// Container child bottombox.Gtk.Box+BoxChild
			this.sensitivity = new global::Gtk.ProgressBar ();
			this.sensitivity.WidthRequest = 100;
			this.sensitivity.Name = "sensitivity";
			this.bottombox.Add (this.sensitivity);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.bottombox [this.sensitivity]));
			w5.Position = 1;
			// Container child bottombox.Gtk.Box+BoxChild
			this.fpslabel = new global::Gtk.Label ();
			this.fpslabel.Name = "fpslabel";
			this.fpslabel.LabelProp = global::Mono.Unix.Catalog.GetString ("60");
			this.bottombox.Add (this.fpslabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.bottombox [this.fpslabel]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child bottombox.Gtk.Box+BoxChild
			this.detect = new global::Gtk.Image ();
			this.detect.WidthRequest = 15;
			this.detect.HeightRequest = 15;
			this.detect.Name = "detect";
			this.bottombox.Add (this.detect);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.bottombox [this.detect]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			// Container child bottombox.Gtk.Box+BoxChild
			this.record = new global::Gtk.Image ();
			this.record.WidthRequest = 15;
			this.record.HeightRequest = 15;
			this.record.Name = "record";
			this.bottombox.Add (this.record);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.bottombox [this.record]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Fill = false;
			this.setBox.Add (this.bottombox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.setBox [this.bottombox]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.fixbox.Add (this.setBox);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixbox [this.setBox]));
			w10.X = 2;
			w10.Y = 126;
			// Container child fixbox.Gtk.Fixed+FixedChild
			this.statsBox = new global::Gtk.Fixed ();
			this.statsBox.WidthRequest = 300;
			this.statsBox.HeightRequest = 30;
			this.statsBox.Name = "statsBox";
			this.statsBox.HasWindow = false;
			// Container child statsBox.Gtk.Fixed+FixedChild
			this.bgstats = new global::Gtk.EventBox ();
			this.bgstats.WidthRequest = 300;
			this.bgstats.HeightRequest = 30;
			this.bgstats.Name = "bgstats";
			// Container child bgstats.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.WidthRequest = 300;
			this.hbox1.HeightRequest = 20;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.IPaddresLabel = new global::Gtk.Label ();
			this.IPaddresLabel.Name = "IPaddresLabel";
			this.IPaddresLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0.0.0.0");
			this.hbox1.Add (this.IPaddresLabel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.IPaddresLabel]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.NameLabel = new global::Gtk.Label ();
			this.NameLabel.Name = "NameLabel";
			this.NameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox1.Add (this.NameLabel);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.NameLabel]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FpsLabel = new global::Gtk.Label ();
			this.FpsLabel.Name = "FpsLabel";
			this.FpsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0 FPS");
			this.hbox1.Add (this.FpsLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FpsLabel]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.bgstats.Add (this.hbox1);
			this.statsBox.Add (this.bgstats);
			this.fixbox.Add (this.statsBox);
			// Container child fixbox.Gtk.Fixed+FixedChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.WidthRequest = 300;
			this.fixed4.HeightRequest = 30;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.optionbox = new global::Gtk.EventBox ();
			this.optionbox.WidthRequest = 500;
			this.optionbox.HeightRequest = 30;
			this.optionbox.Name = "optionbox";
			// Container child optionbox.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.WidthRequest = 300;
			this.vbox3.HeightRequest = 30;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.topbox = new global::Gtk.HBox ();
			this.topbox.Name = "topbox";
			this.topbox.Spacing = 6;
			// Container child topbox.Gtk.Box+BoxChild
			this.source_box = new global::Gtk.ComboBox ();
			this.source_box.WidthRequest = 200;
			this.source_box.Name = "source_box";
			this.topbox.Add (this.source_box);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.topbox [this.source_box]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child topbox.Gtk.Box+BoxChild
			this.MotionButton = new global::Gtk.Button ();
			this.MotionButton.CanFocus = true;
			this.MotionButton.Name = "MotionButton";
			this.MotionButton.UseUnderline = true;
			this.MotionButton.Label = global::Mono.Unix.Catalog.GetString ("Motion");
			this.topbox.Add (this.MotionButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.topbox [this.MotionButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child topbox.Gtk.Box+BoxChild
			this.RecordButton = new global::Gtk.Button ();
			this.RecordButton.CanFocus = true;
			this.RecordButton.Name = "RecordButton";
			this.RecordButton.UseUnderline = true;
			this.RecordButton.Label = global::Mono.Unix.Catalog.GetString ("Record");
			this.topbox.Add (this.RecordButton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.topbox [this.RecordButton]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox3.Add (this.topbox);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.topbox]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			this.optionbox.Add (this.vbox3);
			this.fixed4.Add (this.optionbox);
			this.fixbox.Add (this.fixed4);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixbox [this.fixed4]));
			w23.Y = 20;
			// Container child fixbox.Gtk.Fixed+FixedChild
			this.controls = new global::Gtk.Fixed ();
			this.controls.WidthRequest = 75;
			this.controls.HeightRequest = 75;
			this.controls.Name = "controls";
			this.controls.HasWindow = false;
			// Container child controls.Gtk.Fixed+FixedChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			this.controls.Add (this.eventbox1);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.controls [this.eventbox1]));
			w24.X = -34;
			w24.Y = 61;
			// Container child controls.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button ();
			this.button4.WidthRequest = 30;
			this.button4.HeightRequest = 30;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			this.button4.Image = w25;
			this.controls.Add (this.button4);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.controls [this.button4]));
			w26.X = 24;
			w26.Y = 48;
			// Container child controls.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.WidthRequest = 30;
			this.button3.HeightRequest = 30;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.button3.Image = w27;
			this.controls.Add (this.button3);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.controls [this.button3]));
			w28.X = 45;
			w28.Y = 25;
			// Container child controls.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button ();
			this.button1.WidthRequest = 30;
			this.button1.HeightRequest = 30;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button1.Yalign = 0F;
			global::Gtk.Image w29 = new global::Gtk.Image ();
			w29.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.button1.Image = w29;
			this.controls.Add (this.button1);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.controls [this.button1]));
			w30.Y = 25;
			// Container child controls.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.WidthRequest = 30;
			this.button2.HeightRequest = 30;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button2.Xalign = 0F;
			this.button2.Yalign = 0F;
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			this.button2.Image = w31;
			this.controls.Add (this.button2);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.controls [this.button2]));
			w32.X = 25;
			this.fixbox.Add (this.controls);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixbox [this.controls]));
			w33.X = 268;
			w33.Y = 71;
			this.mainBox.Add (this.fixbox);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.mainBox [this.fixbox]));
			w34.Position = 0;
			this.Add (this.mainBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.topbox.Hide ();
			this.Hide ();
			this.source_box.Changed += new global::System.EventHandler (this.OnSelectDeviceChanged);
			this.MotionButton.Clicked += new global::System.EventHandler (this.OnMotionButtonClicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.button4.Released += new global::System.EventHandler (this.OnButton4Released);
			this.button4.Pressed += new global::System.EventHandler (this.OnButton4Pressed);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button3.Released += new global::System.EventHandler (this.OnButton3Released);
			this.button3.Pressed += new global::System.EventHandler (this.OnButton3Pressed);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button1.Released += new global::System.EventHandler (this.OnButton1Released);
			this.button1.Pressed += new global::System.EventHandler (this.OnButton1Pressed);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button2.Released += new global::System.EventHandler (this.OnButton2Released);
			this.button2.Pressed += new global::System.EventHandler (this.OnButton2Pressed);
		}
	}
}
