
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action FileAction1;
	
	private global::Gtk.Action HelpAction1;
	
	private global::Gtk.Action WindowAction;
	
	private global::Gtk.ToggleAction FullscreenAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.ToggleAction ViewTolboxAction;
	
	private global::Gtk.Action testAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action DevicesSettingsAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar;
	
	private global::Gtk.Table table;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_1;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_2;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_3;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_4;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_5;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_6;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_7;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_8;
	
	private global::QCCTVCameraViewWidget.CameraView VIEW_9;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.HelpAction1 = new global::Gtk.Action ("HelpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction1, null);
		this.WindowAction = new global::Gtk.Action ("WindowAction", global::Mono.Unix.Catalog.GetString ("Window"), null, null);
		this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Window");
		w1.Add (this.WindowAction, null);
		this.FullscreenAction = new global::Gtk.ToggleAction ("FullscreenAction", global::Mono.Unix.Catalog.GetString ("Fullscreen"), null, null);
		this.FullscreenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fullscreen");
		w1.Add (this.FullscreenAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.ViewTolboxAction = new global::Gtk.ToggleAction ("ViewTolboxAction", global::Mono.Unix.Catalog.GetString ("View Tolbox"), null, null);
		this.ViewTolboxAction.Active = true;
		this.ViewTolboxAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Tolbox");
		w1.Add (this.ViewTolboxAction, null);
		this.testAction = new global::Gtk.Action ("testAction", global::Mono.Unix.Catalog.GetString ("test"), null, null);
		this.testAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("test");
		w1.Add (this.testAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.DevicesSettingsAction = new global::Gtk.Action ("DevicesSettingsAction", global::Mono.Unix.Catalog.GetString ("Devices Settings"), null, null);
		this.DevicesSettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Devices Settings");
		w1.Add (this.DevicesSettingsAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1024;
		this.HeightRequest = 768;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("QCCTV Center");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar'><menu name='FileAction1' action='FileAction1'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='DevicesSettingsAction' action='DevicesSettingsAction'/></menu><menu name='WindowAction' action='WindowAction'><menuitem name='FullscreenAction' action='FullscreenAction'/><menuitem name='ViewTolboxAction' action='ViewTolboxAction'/></menu><menu name='HelpAction1' action='HelpAction1'/></menubar></ui>");
		this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
		this.menubar.Name = "menubar";
		this.vbox1.Add (this.menubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
		this.table.Name = "table";
		// Container child table.Gtk.Table+TableChild
		this.VIEW_1 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_1.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_1.Name = "VIEW_1";
		this.VIEW_1.fps = 0;
		this.VIEW_1.controlVisible = false;
		this.VIEW_1.width = 0;
		this.VIEW_1.height = 0;
		this.table.Add (this.VIEW_1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_1]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_2 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_2.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_2.Name = "VIEW_2";
		this.VIEW_2.fps = 0;
		this.VIEW_2.controlVisible = false;
		this.VIEW_2.width = 0;
		this.VIEW_2.height = 0;
		this.table.Add (this.VIEW_2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_2]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_3 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_3.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_3.Name = "VIEW_3";
		this.VIEW_3.fps = 0;
		this.VIEW_3.controlVisible = false;
		this.VIEW_3.width = 0;
		this.VIEW_3.height = 0;
		this.table.Add (this.VIEW_3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_3]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_4 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_4.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_4.Name = "VIEW_4";
		this.VIEW_4.fps = 0;
		this.VIEW_4.controlVisible = false;
		this.VIEW_4.width = 0;
		this.VIEW_4.height = 0;
		this.table.Add (this.VIEW_4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_4]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_5 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_5.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_5.Name = "VIEW_5";
		this.VIEW_5.fps = 0;
		this.VIEW_5.controlVisible = false;
		this.VIEW_5.width = 0;
		this.VIEW_5.height = 0;
		this.table.Add (this.VIEW_5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_6 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_6.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_6.Name = "VIEW_6";
		this.VIEW_6.fps = 0;
		this.VIEW_6.controlVisible = false;
		this.VIEW_6.width = 0;
		this.VIEW_6.height = 0;
		this.table.Add (this.VIEW_6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_6]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_7 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_7.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_7.Name = "VIEW_7";
		this.VIEW_7.fps = 0;
		this.VIEW_7.controlVisible = false;
		this.VIEW_7.width = 0;
		this.VIEW_7.height = 0;
		this.table.Add (this.VIEW_7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_7]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_8 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_8.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_8.Name = "VIEW_8";
		this.VIEW_8.fps = 0;
		this.VIEW_8.controlVisible = false;
		this.VIEW_8.width = 0;
		this.VIEW_8.height = 0;
		this.table.Add (this.VIEW_8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_8]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.VIEW_9 = new global::QCCTVCameraViewWidget.CameraView ();
		this.VIEW_9.Events = ((global::Gdk.EventMask)(256));
		this.VIEW_9.Name = "VIEW_9";
		this.VIEW_9.fps = 0;
		this.VIEW_9.controlVisible = false;
		this.VIEW_9.width = 0;
		this.VIEW_9.height = 0;
		this.table.Add (this.VIEW_9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table [this.VIEW_9]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table]));
		w12.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1024;
		this.DefaultHeight = 768;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.EntryKeyPressEvent);
		this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.EntryKeyUpEvent);
		this.FullscreenAction.Toggled += new global::System.EventHandler (this.OnMenuActionFullScreenTogle);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnMenuActionExit);
		this.ViewTolboxAction.Toggled += new global::System.EventHandler (this.OnMenuActionTooboxVisibleTogle);
		this.DevicesSettingsAction.Activated += new global::System.EventHandler (this.OnMenuActionShowDevicesSettings);
	}
}
