
// This file has been generated by the GUI designer. Do not modify.
namespace QCCTV
{
	public partial class DevicesSettingsWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView deviceListsBox;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.Button editButton;
		
		private global::Gtk.Button removeButton;
		
		private global::Gtk.Fixed fixed8;
		
		private global::Gtk.HBox SettingsBox;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox devSettingsBox;
		
		private global::Gtk.Fixed fixed5;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Entry nameField;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox driverListBox;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hardwareBox;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.ComboBox hardwareListBox;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.HBox uriBox;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry uriField;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox loginBox;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry loginField;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.HBox passwordBox;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry passwordField;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.CheckButton bControls;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Fixed fixed7;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView logView;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Button testButton;
		
		private global::Gtk.Button saveButton;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QCCTV.DevicesSettingsWindow
			this.WidthRequest = 1024;
			this.HeightRequest = 768;
			this.Name = "QCCTV.DevicesSettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DevicesSettingsWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child QCCTV.DevicesSettingsWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Devices");
			this.vbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.deviceListsBox = new global::Gtk.TreeView ();
			this.deviceListsBox.CanFocus = true;
			this.deviceListsBox.Name = "deviceListsBox";
			this.GtkScrolledWindow.Add (this.deviceListsBox);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Add Device");
			this.hbox7.Add (this.button2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.editButton = new global::Gtk.Button ();
			this.editButton.Sensitive = false;
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			this.editButton.Label = global::Mono.Unix.Catalog.GetString ("Edit Device Settings");
			this.hbox7.Add (this.editButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.editButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.removeButton = new global::Gtk.Button ();
			this.removeButton.Sensitive = false;
			this.removeButton.CanFocus = true;
			this.removeButton.Name = "removeButton";
			this.removeButton.UseUnderline = true;
			this.removeButton.Label = global::Mono.Unix.Catalog.GetString ("Remove Device");
			this.hbox7.Add (this.removeButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.removeButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox6.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox4]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed ();
			this.fixed8.WidthRequest = 10;
			this.fixed8.HeightRequest = 720;
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.hbox6.Add (this.fixed8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed8]));
			w9.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.SettingsBox = new global::Gtk.HBox ();
			this.SettingsBox.Sensitive = false;
			this.SettingsBox.Name = "SettingsBox";
			this.SettingsBox.Spacing = 6;
			// Container child SettingsBox.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.WidthRequest = 10;
			this.fixed3.HeightRequest = 720;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.SettingsBox.Add (this.fixed3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.SettingsBox [this.fixed3]));
			w10.Position = 0;
			// Container child SettingsBox.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.devSettingsBox = new global::Gtk.VBox ();
			this.devSettingsBox.Name = "devSettingsBox";
			this.devSettingsBox.Spacing = 6;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.HeightRequest = 10;
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.devSettingsBox.Add (this.fixed5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.fixed5]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.WidthRequest = 200;
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Device Name");
			this.hbox15.Add (this.label13);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label13]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.nameField = new global::Gtk.Entry ();
			this.nameField.WidthRequest = 300;
			this.nameField.CanFocus = true;
			this.nameField.Name = "nameField";
			this.nameField.IsEditable = true;
			this.nameField.InvisibleChar = '●';
			this.hbox15.Add (this.nameField);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.nameField]));
			w13.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.WidthRequest = 180;
			this.label14.Name = "label14";
			this.hbox15.Add (this.label14);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label14]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.devSettingsBox.Add (this.hbox15);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.hbox15]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 200;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Driver");
			this.hbox10.Add (this.label3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label3]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.driverListBox = new global::Gtk.ComboBox ();
			this.driverListBox.WidthRequest = 300;
			this.driverListBox.Name = "driverListBox";
			this.driverListBox.HasFrame = false;
			this.hbox10.Add (this.driverListBox);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.driverListBox]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 180;
			this.label4.Name = "label4";
			this.hbox10.Add (this.label4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label4]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.devSettingsBox.Add (this.hbox10);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.hbox10]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.hardwareBox = new global::Gtk.HBox ();
			this.hardwareBox.Name = "hardwareBox";
			this.hardwareBox.Spacing = 6;
			// Container child hardwareBox.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.WidthRequest = 200;
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Hardware");
			this.hardwareBox.Add (this.label15);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hardwareBox [this.label15]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hardwareBox.Gtk.Box+BoxChild
			this.hardwareListBox = new global::Gtk.ComboBox ();
			this.hardwareListBox.WidthRequest = 300;
			this.hardwareListBox.Name = "hardwareListBox";
			this.hardwareListBox.HasFrame = false;
			this.hardwareBox.Add (this.hardwareListBox);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hardwareBox [this.hardwareListBox]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hardwareBox.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.WidthRequest = 180;
			this.label16.Name = "label16";
			this.hardwareBox.Add (this.label16);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hardwareBox [this.label16]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.devSettingsBox.Add (this.hardwareBox);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.hardwareBox]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.uriBox = new global::Gtk.HBox ();
			this.uriBox.Name = "uriBox";
			this.uriBox.Spacing = 6;
			// Container child uriBox.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 200;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("URI");
			this.uriBox.Add (this.label5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.uriBox [this.label5]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child uriBox.Gtk.Box+BoxChild
			this.uriField = new global::Gtk.Entry ();
			this.uriField.WidthRequest = 300;
			this.uriField.CanFocus = true;
			this.uriField.Name = "uriField";
			this.uriField.IsEditable = true;
			this.uriField.InvisibleChar = '●';
			this.uriBox.Add (this.uriField);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.uriBox [this.uriField]));
			w25.Position = 1;
			// Container child uriBox.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 180;
			this.label6.Name = "label6";
			this.uriBox.Add (this.label6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.uriBox [this.label6]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.devSettingsBox.Add (this.uriBox);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.uriBox]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.loginBox = new global::Gtk.HBox ();
			this.loginBox.Name = "loginBox";
			this.loginBox.Spacing = 6;
			// Container child loginBox.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 200;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Login");
			this.loginBox.Add (this.label7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.loginBox [this.label7]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child loginBox.Gtk.Box+BoxChild
			this.loginField = new global::Gtk.Entry ();
			this.loginField.WidthRequest = 300;
			this.loginField.CanFocus = true;
			this.loginField.Name = "loginField";
			this.loginField.IsEditable = true;
			this.loginField.InvisibleChar = '●';
			this.loginBox.Add (this.loginField);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.loginBox [this.loginField]));
			w29.Position = 1;
			// Container child loginBox.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.WidthRequest = 180;
			this.label8.Name = "label8";
			this.loginBox.Add (this.label8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.loginBox [this.label8]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.devSettingsBox.Add (this.loginBox);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.loginBox]));
			w31.Position = 5;
			w31.Expand = false;
			w31.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.passwordBox = new global::Gtk.HBox ();
			this.passwordBox.Name = "passwordBox";
			this.passwordBox.Spacing = 6;
			// Container child passwordBox.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 200;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.passwordBox.Add (this.label9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.passwordBox [this.label9]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child passwordBox.Gtk.Box+BoxChild
			this.passwordField = new global::Gtk.Entry ();
			this.passwordField.WidthRequest = 300;
			this.passwordField.CanFocus = true;
			this.passwordField.Name = "passwordField";
			this.passwordField.IsEditable = true;
			this.passwordField.InvisibleChar = '●';
			this.passwordBox.Add (this.passwordField);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.passwordBox [this.passwordField]));
			w33.Position = 1;
			// Container child passwordBox.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 180;
			this.label10.Name = "label10";
			this.passwordBox.Add (this.label10);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.passwordBox [this.label10]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.devSettingsBox.Add (this.passwordBox);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.passwordBox]));
			w35.Position = 6;
			w35.Expand = false;
			w35.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.WidthRequest = 200;
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Controls");
			this.hbox2.Add (this.label17);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label17]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.bControls = new global::Gtk.CheckButton ();
			this.bControls.CanFocus = true;
			this.bControls.Name = "bControls";
			this.bControls.Label = global::Mono.Unix.Catalog.GetString ("checkbutton1");
			this.bControls.DrawIndicator = true;
			this.bControls.UseUnderline = true;
			this.hbox2.Add (this.bControls);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.bControls]));
			w37.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 180;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.devSettingsBox.Add (this.hbox2);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.hbox2]));
			w39.Position = 7;
			w39.Expand = false;
			w39.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.HeightRequest = 200;
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.devSettingsBox.Add (this.fixed7);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.fixed7]));
			w40.Position = 8;
			w40.Expand = false;
			w40.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
			this.devSettingsBox.Add (this.label11);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.label11]));
			w41.Position = 9;
			w41.Expand = false;
			w41.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.logView = new global::Gtk.TextView ();
			this.logView.HeightRequest = 100;
			this.logView.CanFocus = true;
			this.logView.Name = "logView";
			this.GtkScrolledWindow1.Add (this.logView);
			this.devSettingsBox.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.GtkScrolledWindow1]));
			w43.Position = 10;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.WidthRequest = 690;
			this.fixed4.HeightRequest = 20;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.devSettingsBox.Add (this.fixed4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.fixed4]));
			w44.Position = 11;
			w44.Expand = false;
			w44.Fill = false;
			// Container child devSettingsBox.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.WidthRequest = 600;
			this.label12.Name = "label12";
			this.hbox14.Add (this.label12);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label12]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.testButton = new global::Gtk.Button ();
			this.testButton.CanFocus = true;
			this.testButton.Name = "testButton";
			this.testButton.UseUnderline = true;
			this.testButton.Label = global::Mono.Unix.Catalog.GetString ("Test");
			this.hbox14.Add (this.testButton);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.testButton]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseUnderline = true;
			this.saveButton.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbox14.Add (this.saveButton);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.saveButton]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			this.devSettingsBox.Add (this.hbox14);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.devSettingsBox [this.hbox14]));
			w48.Position = 12;
			w48.Expand = false;
			w48.Fill = false;
			this.GtkAlignment.Add (this.devSettingsBox);
			this.frame2.Add (this.GtkAlignment);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Device Settings");
			this.GtkLabel6.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel6;
			this.SettingsBox.Add (this.frame2);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.SettingsBox [this.frame2]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			this.hbox6.Add (this.SettingsBox);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.SettingsBox]));
			w52.Position = 2;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
			w54.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.hbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.Shown += new global::System.EventHandler (this.OnShowWindow);
			this.deviceListsBox.SelectCursorRow += new global::Gtk.SelectCursorRowHandler (this.OnSelectDeviceChanged);
			this.deviceListsBox.CursorChanged += new global::System.EventHandler (this.OnSelectDeviceChanged);
			this.button2.Clicked += new global::System.EventHandler (this.OnAddDeviceButton);
			this.editButton.Clicked += new global::System.EventHandler (this.OnEditDeviceButton);
			this.nameField.Changed += new global::System.EventHandler (this.OnNameChanged);
			this.driverListBox.Changed += new global::System.EventHandler (this.OnDriverChanged);
			this.hardwareListBox.Changed += new global::System.EventHandler (this.OnDriverChanged);
			this.uriField.Changed += new global::System.EventHandler (this.OnUriChanged);
			this.loginField.Changed += new global::System.EventHandler (this.OnLoginChanged);
			this.passwordField.Changed += new global::System.EventHandler (this.OnPasswordChanged);
			this.testButton.Clicked += new global::System.EventHandler (this.OnTestDevice);
			this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveDeviceNow);
			this.button1.Clicked += new global::System.EventHandler (this.OnCloseButton);
		}
	}
}
